### ISSUE TITLE
Update Workflow scripts

### ISSUE THREAD

**Issue by alxjrvs** [TheGnarCo/.github#3]
Patterns and standards have changed since we added these scripts. we should run through to make sure they are up to date, creating and altering as we see fit.

**Comment by alxjrvs** [comment]
This can (should?) be brought up to date by multiple people.

**Comment by alxjrvs** [comment]
Things that would be useful to check: 
 - node / ruby versions 
 - latest version of any associated plugins 
 - are we missing anything ("Now we use Prettier in ruby, so we shoudl drop rubocop..." or something) 
 - GHA optimizations (Do we need a DB? Can we make anything more dynamic?)

**Comment by WMahoney09** [comment]
Job-Board (rails & react) action version updates: https://gnardog.slack.com/archives/C7NJ4UWJY/p1706284993853679
